### ISSUE TITLE
Failed to set up - HA  2023.5.0b3

### ISSUE THREAD

**Issue by rodgrech** [lewei50/ha_iammeter#5]
hi guys, having issues with the integration starting in 2023.5.0b3
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230428.0 - latest

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/iammeter_http/__init__.py", line 25, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by soheiladeli** [comment]
Has the same issue with the home assistant core integration 2023.5.0. The HACS integration fails to set up:
Home Assistant core 2023.5.0
Frontend 20230503.1 - latest

Logger: homeassistant.config_entries
Source: custom_components/iammeter_http/__init__.py:25
Integration: Iammeter_http
First occurred: 5:10:34 PM (1 occurrences)
Last logged: 5:10:34 PM

Error setting up entry i_meter_fc621daa for iammeter_http
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/root/.homeassistant/custom_components/iammeter_http/__init__.py", line 25, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by tobuser** [comment]
same here

**Comment by grahambrown11** [comment]
Hey @rodgrech @soheiladeli & @tobuser check my quick fix here:
https://github.com/lewei50/ha_iammeter/issues/6#issuecomment-1537127616
